services:
  web:
    build: .
    container_name: site-partoches
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    user: "33:33"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: dbPartoches
    networks:
      - partoches-net

  db:
    image: mariadb:latest
    container_name: my-mariadb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dbPartoches
    volumes:
      - db_data:/var/lib/mysql
      - ./dbPartoches.sql:/docker-entrypoint-initdb.d/dbPartoches.sql
    networks:
      - partoches-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: site-phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - partoches-net

networks:
  partoches-net:
    driver: bridge

volumes:
  db_data:
  data_volume: